axis_linear: 1  # Left thumb stick vertical
scale_linear: 0.1
scale_linear_turbo: 1.5

axis_angular: 0  # Left thumb stick horizontal
scale_angular: 0.6

enable_button: 2  # Left trigger button
enable_turbo_button: 5  # Right trigger button

ang_increase_button: 14
ang_decrease_button: 13

line_increase_button: 15
line_decrease_button: 16

delta_value: 0.05
line_speed_ceil: 2.0
ang_speed_ceil: 4.0

shutdown_button: 8
start_button: 9
wait_times: 100
